#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
MAC_ADDR=$(ifconfig br-lan | grep -oE '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
# 格式化MAC地址去掉冒号
FORMATTED_MAC=$(echo $MAC_ADDR | sed 's/://g')
SALTID="ID"
SALTPASS="mspasswrd"
ID=$(echo -n "${FORMATTED_MAC}${SALTID}" | md5sum | cut -c1-8)
ROOT_PASSWORD=$(echo -n "${ID}${SALTPASS}" | md5sum | cut -c1-8)
echo -e "$ROOT_PASSWORD\n$ROOT_PASSWORD" | (passwd root)
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='250101'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='MS校园网&闲鱼MSWIFI路由器 @ $ID&'" >> /etc/openwrt_release
echo "DISTRIB_TARGET='$ID'" >> /etc/openwrt_release
sed -i "s/option force_dns '0'/option force_dns '1'/" /etc/config/https-dns-proxy
sed -i "s/option enable '1'/option enable '0'/" /etc/config/scutclient
rm -f /etc/init.d/msstart




